### ISSUE TITLE
eine sehr große Bitte

### ISSUE THREAD

**Issue by vlv993** [benzac-de/msx#1]
добрий день. ви є розробником MSX? дуже велике прохання є до вас: зробіть будь ласка щоб пауза в плеєрі включалась при одиночному нажиманні кнопки "ОК" на пульті телевізора. в мене на пульті немає окремої кнопки "плей/пауза" , а нажимати 2 рази "ок" не дуже зручно ) 

good day. are you an MSX developer? I have a very big request for you: please make the pause in the player turn on when you press the "OK" button on the TV remote once. I don't have a separate "play/pause" button on my remote, and pressing "ok" twice is not very convenient) 

guten Tag. Sind Sie ein MSX-Entwickler? Ich habe eine sehr große Bitte an Sie: Bitte lassen Sie die Pause im Player einschalten, wenn Sie einmal die „OK“-Taste auf der TV-Fernbedienung drücken. Ich habe keine separate "Wiedergabe/Pause"-Taste auf meiner Fernbedienung, und das zweimalige Drücken von "OK" ist nicht sehr praktisch.)
Написать в Media Station X

**Comment by benzac-de** [comment]
Thank you for your request. 
This behavior can already be achieved by using extended properties. Please have a look at the 6th example (Video 6) on the following wiki page: https://msx.benzac.de/wiki/index.php?title=Extended_Properties

**Comment by vlv993** [comment]
Thanks a lot for your answer. I'm not a programmer, but an ordinary lg TV
user. and unfortunately I can’t figure out what to do to make the pause
work on a single click on the “ok” button. if it doesn't bother you -
explain in more detail, can I do this in the msx settings?

пт, 2 сент. 2022 г. в 13:35, benzac ***@***.***>:

**Comment by benzac-de** [comment]
Currently, only the MSX content creator can provide this behavior. It would also be possible to simply assign a color key (red, green, yellow) or a number key (0 - 9) to the play/pause action. However, also this can only be done by the MSX content creator.

**Comment by vlv993** [comment]
thanks for you ansfer )
