### ISSUE TITLE
[FEATURE-REQUEST] [QUESTION] Media Station X Client for Apple TV > Plans

### ISSUE THREAD

**Issue by MetaChuh** [benzac-de/msx#10]
hi @benzac-de 

are there any plans to release a media station x for apple tv ?
or does the base code contain methods, that prevent a publishing for tvos devices, at the apple app store ?

thx & greetings,
metachuh

**Comment by benzac-de** [comment]
html,body{background-color:#fff;color:#333;line-height:1.4;font-family:sans-serif,Arial,Verdana,Trebuchet MS;}
Hello,
 
Thank you for your request.
Unfortunately, Apple TVs currently do not support WebViews (which are required to run Media Station X).
Therefore, an application for Apple TVs cannot be provided right now.
There are some projects on GitHub (e.g. https://github.com/jvanakker/tvOSBrowser) that use a hack to make a browser available on Apple TVs. However, Apple will not allow something like this for the store.
 
Best regards,
benzac

MetaChuh schrieb am 23.04.2024 05:25 (GMT +02:00):

hi @benzac-de
are there any plans to release a media station x for apple tv ?or does the base code contain methods, that prevent a publishing for tvos devices, at the apple app store ?
thx & greetings,metachuh
