### ISSUE TITLE
add a way to implement multi users and password stuff

### ISSUE THREAD

**Issue by NeLagina** [benzac-de/msx#5]
soo it would help like do favorited movie resume movie / video 
for more than all devices

**Comment by TheoAnastasiadis** [comment]
@bzachey 's system is very well made and has very powerful features with good developer experience so I'd suggest you try and make what you need on your own. Authentication can be very easily implemented with the `execute:service` action. I learned a lot with this project, maybe you can too!

**Comment by NeLagina** [comment]
i don't know how can you lead me how could i do it ? :\

**Comment by NeLagina** [comment]
@benzac-de question how to use execute:code:user: because it uses php but php has only json  soo yeah .........

**Comment by NeLagina** [comment]
SOME NEWS you can use http api server of python soo yeah

**Comment by benzac-de** [comment]
All server actions can be used with any server endpoint (written in PHP, Node.js script, Java HttpServlet, etc.). For server actions, the MSX application always sends HTTP POST requests with a JSON object. Please see following wiki page for the different JSON structures: https://msx.benzac.de/wiki/index.php?title=Attached_Data_Examples

To implement such kind of service, you need basic backend programming knowledge.
