### ISSUE TITLE
Make that we can make the MENU  head line a img 

### ISSUE THREAD

**Issue by NeLagina** [benzac-de/msx#6]
soo implement a way to add a nice headline img soo it would be like  discord
![image](https://github.com/benzac-de/msx/assets/108587963/c9f9069e-76d2-4b40-bb74-df26d90acd4e)

**Comment by benzac-de** [comment]
Have you already tried to use the `logo` property?
Reference: https://msx.benzac.de/wiki/index.php?title=Menu_Root_Object

**Comment by NeLagina** [comment]
i dumb did not see that ; \ thanks again ...
