### ISSUE TITLE
variables  ?

### ISSUE THREAD

**Issue by NeLagina** [benzac-de/msx#7]
how can i make variables from python server respond because i want that media station know  or save like id of numbers 
i want that media station has custom id that i can get it send it to the server went need and send need info to media sation

**Comment by benzac-de** [comment]
The classical way would be to use persistent cookies. Alternatively, you can use the MSX ID for each request (i.e. use the {ID} keyword), which is an automatically generated unique ID for each device: https://msx.benzac.de/wiki/index.php?title=Requests

**Comment by NeLagina** [comment]
ok :)
