### ISSUE TITLE
Why does video work on phone only / tv ? 

### ISSUE THREAD

**Issue by NeLagina** [benzac-de/msx#8]
soo i getting some problems using media station x
when i use my phone / tv the video support everything works but when i use the computer app version and the web version it dosen't support it says 

how to recreate?
use this video link https://imgsto.re/api/7/01/9BRwO8eZo0wfFVSjgL21FQ/0362227/1709941918.mp4

**Comment by NeLagina** [comment]
![image](https://github.com/benzac-de/msx/assets/108587963/16595c86-8272-4d6e-9fb4-e05d70549d4b)

**Comment by TheoAnastasiadis** [comment]
@NeLagina Looks like the video does not exist anymore (?) 
![410](https://github.com/benzac-de/msx/assets/31965686/08e9a8a5-1bc4-40d6-9e2c-cb94f247636a)

**Comment by NeLagina** [comment]
It exits but fod somd reason computer and other devices that usd the video link can't see that but when i use media station x it lets TVs and phones to watch

**Comment by NeLagina** [comment]
Soo FOUND the problem it for some reason check the size if its big some reasolution it canceles the thing but it works if the resolution of the thing is lower soo yeah
