### ISSUE TITLE
Cookies using php 

### ISSUE THREAD

**Issue by NeLagina** [benzac-de/msx#9]
want to use cookies for auto login for user system but php say it disabled soo yeah , using "execute:user:https://redacted.php"

**Comment by benzac-de** [comment]
Please ensure that you set the correct headers when using the `user:` prefix (i.e. `Access-Control-Allow-Credentials: true`). For PHP, the header section might look like this.

```
header('Access-Control-Allow-Origin: ' . $_SERVER['HTTP_ORIGIN']);
header('Access-Control-Allow-Headers: Origin, Content-Type, Accept');
header('Access-Control-Allow-Methods: GET, POST, OPTIONS');
header('Access-Control-Allow-Credentials: true');
header('Content-Type: application/json');
```

Please also note that Android devices (and most modern browsers) follow the SameSite cookie policy (https://developers.google.com/search/blog/2020/01/get-ready-for-new-samesitenone-secure). Therefore, it is recommended to set cookies via HTTPS with `SameSite=None` and the `Secure` flag (e.g. `Set-Cookie: key=value; SameSite=None; Secure`). For PHP, the session section might look like this.

```
if (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off') {
    session_set_cookie_params([
        'secure' => true,
        'samesite' => 'none'
    ]);
}
```

Best regards,
benzac

**Comment by NeLagina** [comment]
Ok gona look into it

**Comment by NeLagina** [comment]
uhh for the cookies your wear right but a small question is it possible that msx uses start.php because start.json its getting some cors errors . I just asking to add support to start.php because with that i could enable cors and it would work again in web 
:)

**Comment by benzac-de** [comment]
You can use the syntax `id:php:{SERVER}` (e.g. `id:php:example.com` → `http://example.com/msx/start.php`) to load your start object from a PHP file.
Alternatively, if you would like to host the start object under a specific path or you need a specific query, you can use a URL shortener service: https://msx.benzac.de/wiki/index.php?title=Setup_Start_Parameter#URL_Shortener_Services

**Comment by NeLagina** [comment]
Hmm ,nice gona try it out :)
